"""Default consumer persona coverage for the marketing sandbox."""

from __future__ import annotations

from .consumer_agent import Persona


# These are benefit-led coverage archetypes. Scenario cards supply the
# person-situation pressure needed for a concrete sandbox run.
DEFAULT_CONSUMER_PERSONA_IDS: tuple[str, ...] = (
    "value-pragmatist",
    "deal-explorer",
    "trust-first",
    "convenience-saver",
    "habit-repeat",
    "outcome-optimizer",
    "novelty-seeker",
    "social-proof-comparer",
    "identity-expresser",
    "occasion-buyer",
)


DEFAULT_CONSUMER_PERSONAS: tuple[Persona, ...] = (
    Persona(
        name="Value-constrained pragmatist",
        core_need="A choice that solves the job without straining the budget.",
        purchase_motivation="Clear everyday value and a low feeling of waste.",
        current_alternative="A cheaper familiar substitute or doing without.",
        price_sensitivity="Budget-led and notices full out-of-pocket cost first.",
        trust_sensitivity="Needs enough proof to avoid wasting limited money.",
        promotion_sensitivity="Responds when an offer makes value easier to verify.",
        channel_preference="Comparison-friendly channels with transparent costs.",
        social_influence="Uses reviews to check whether claimed value is real.",
        main_barrier="The offer feels like an avoidable extra expense.",
        repeat_trigger="The product proves useful in a recurring routine.",
        switching_threshold="Will leave if a substitute keeps the job solved for less hassle or spend.",
    ),
    Persona(
        name="Deal-triggered explorer",
        core_need="A safe excuse to try something new without overcommitting.",
        purchase_motivation="A timely deal that turns curiosity into trial.",
        current_alternative="Browsing launches and waiting for a better entry offer.",
        price_sensitivity="Trial-sensitive more than permanently bargain-only.",
        trust_sensitivity="Needs guardrails when novelty claims feel thin.",
        promotion_sensitivity="Highly alert to trial packs, coupons, and launch bundles.",
        channel_preference="Fast discovery channels where offers are easy to redeem.",
        social_influence="Trend chatter can create curiosity but not durable trust alone.",
        main_barrier="The brand may be using incentives to hide weak product fit.",
        repeat_trigger="The first use creates a reason beyond the original deal.",
        switching_threshold="Will chase the next trial if value disappears after promotion.",
    ),
    Persona(
        name="Trust-first risk reducer",
        core_need="Confidence that the product and seller will not create regret.",
        purchase_motivation="Credible proof, transparent boundaries, and reassurance.",
        current_alternative="A known brand with stronger familiarity and service history.",
        price_sensitivity="Will not pay blindly, but risk matters before small savings.",
        trust_sensitivity="Very sensitive to evidence, guarantees, and overclaims.",
        promotion_sensitivity="Discounts help only after trust signals look legitimate.",
        channel_preference="Trusted channels with clear service and information trails.",
        social_influence="Weights credible reviews and expert-like proof over buzz.",
        main_barrier="Unclear claims or support make the first move feel risky.",
        repeat_trigger="A dependable first experience confirms the promise.",
        switching_threshold="Returns to known competitors when proof or service weakens.",
    ),
    Persona(
        name="Convenience-first time saver",
        core_need="A solution that removes effort from an already busy moment.",
        purchase_motivation="Speed, access, clarity, and a friction-light path.",
        current_alternative="The quickest option already embedded in the routine.",
        price_sensitivity="Will notice price but often trades some spend for less effort.",
        trust_sensitivity="Needs the easy path to still feel reliable.",
        promotion_sensitivity="Ignores offers that add steps, rules, or waiting.",
        channel_preference="Fast purchase and delivery paths with few decisions.",
        social_influence="Checks social proof only when it reduces search time.",
        main_barrier="Learning, registration, waiting, or channel friction.",
        repeat_trigger="The product becomes the easiest repeat action.",
        switching_threshold="Switches when another route is materially faster or simpler.",
    ),
    Persona(
        name="Habit-anchored repeater",
        core_need="Continuity in a routine that already works well enough.",
        purchase_motivation="Stable repeat value with minimal switching disruption.",
        current_alternative="The incumbent product already used by default.",
        price_sensitivity="Not deal-chasing unless the routine cost clearly worsens.",
        trust_sensitivity="Trust is embedded in past experience and predictability.",
        promotion_sensitivity="Acquisition offers rarely beat a strong old habit alone.",
        channel_preference="The repeat channel already tied to the habit loop.",
        social_influence="Social cues matter less than personal repeat experience.",
        main_barrier="There is no strong reason to break the old loop.",
        repeat_trigger="A cue, replenishment moment, or calendar rhythm repeats naturally.",
        switching_threshold="Moves only when the new path is clearly easier, safer, or more fitting.",
    ),
    Persona(
        name="Outcome-focused optimizer",
        core_need="The best fit for a concrete result or performance job.",
        purchase_motivation="Specific benefits, evidence, and tradeoff clarity.",
        current_alternative="Comparing specs, evidence, and specialist alternatives.",
        price_sensitivity="Judges price against outcome quality rather than alone.",
        trust_sensitivity="Needs claims linked to proof and product boundaries.",
        promotion_sensitivity="Promotion can start a look but not replace evidence.",
        channel_preference="Information-rich channels that support comparison.",
        social_influence="Trusts informed reviews more than generic popularity.",
        main_barrier="Benefits sound vague or unrelated to the real job.",
        repeat_trigger="The outcome is repeatably delivered in the target use case.",
        switching_threshold="Changes when another option demonstrates a better fit for the job.",
    ),
    Persona(
        name="Novelty experience seeker",
        core_need="A fresh experience worth attention and conversation.",
        purchase_motivation="Newness, sensory interest, or a memorable use moment.",
        current_alternative="Rotating among new launches and experiences.",
        price_sensitivity="Accepts some novelty premium when the experience is clear.",
        trust_sensitivity="Still rejects novelty that feels careless or misleading.",
        promotion_sensitivity="Responds to launches and vivid demonstrations.",
        channel_preference="Discovery-heavy channels with strong experience cues.",
        social_influence="Friends and creators can spark trial when experience is legible.",
        main_barrier="The newness is only packaging and not a real experience.",
        repeat_trigger="Novelty converts into an occasion worth repeating.",
        switching_threshold="Leaves when a competing experience feels fresher or more memorable.",
    ),
    Persona(
        name="Social-proof comparer",
        core_need="Reassurance that other relevant people have validated the choice.",
        purchase_motivation="Visible adoption, credible reviews, and consensus cues.",
        current_alternative="Waiting, comparing reviews, or following better-established options.",
        price_sensitivity="Interprets extreme price signals through social credibility.",
        trust_sensitivity="Highly sensitive to review quality and manipulated-looking proof.",
        promotion_sensitivity="Offers help when they do not undermine credibility.",
        channel_preference="Channels where reviews and comparison context are visible.",
        social_influence="Social proof is central, especially from similar users.",
        main_barrier="Proof looks sparse, fake, or from the wrong reference group.",
        repeat_trigger="Own experience matches the outside validation.",
        switching_threshold="Moves when competitor proof becomes more credible and relevant.",
    ),
    Persona(
        name="Identity meaning expresser",
        core_need="A choice that fits self-image, values, or group belonging.",
        purchase_motivation="Meaningful positioning and a product role worth identifying with.",
        current_alternative="Brands or rituals that already express the desired identity.",
        price_sensitivity="Price is interpreted through meaning and authenticity.",
        trust_sensitivity="Rejects symbolic claims that feel opportunistic.",
        promotion_sensitivity="Promotions must preserve identity and brand tone.",
        channel_preference="Touchpoints that let story and usage context breathe.",
        social_influence="Cares about reference groups and cultural fit, not raw buzz.",
        main_barrier="The brand voice feels generic or inauthentic.",
        repeat_trigger="Use reinforces identity in repeated situations.",
        switching_threshold="Leaves when another brand expresses the meaning more credibly.",
    ),
    Persona(
        name="Occasion relationship buyer",
        core_need="A product that fits a social moment, gift, or shared occasion.",
        purchase_motivation="Reduce awkwardness and make the occasion feel right.",
        current_alternative="Safer familiar gifts, host choices, or no purchase.",
        price_sensitivity="Judges spend against the importance of the occasion.",
        trust_sensitivity="Needs presentation, timing, and reliability to feel safe.",
        promotion_sensitivity="Occasion bundles help when they simplify the decision.",
        channel_preference="Channels that support timing, presentation, and delivery confidence.",
        social_influence="Imagines recipient and group reaction before deciding.",
        main_barrier="The choice may miss the moment or send the wrong signal.",
        repeat_trigger="Another similar occasion reactivates the need.",
        switching_threshold="Switches when competitors make the occasion fit clearer and safer.",
    ),
)


DEFAULT_CONSUMER_PERSONA_BY_ID: dict[str, Persona] = dict(
    zip(DEFAULT_CONSUMER_PERSONA_IDS, DEFAULT_CONSUMER_PERSONAS, strict=True)
)
