import { SANDBOX_EVENT_TYPES } from "./event-schema.js";

export const SAMPLE_AGENTS = Object.freeze([
  {
    id: "decision",
    name: "DecisionAgent",
    role: "decision",
    color: "#f7d887",
  },
  {
    id: "consumer-value",
    name: "预算价值务实者",
    role: "consumer",
    color: "#7dc9b9",
  },
  {
    id: "consumer-deal",
    name: "优惠触发尝鲜者",
    role: "consumer",
    color: "#a3dfbb",
  },
  {
    id: "consumer-trust",
    name: "信任风险谨慎者",
    role: "consumer",
    color: "#85a9d9",
  },
  {
    id: "consumer-convenience",
    name: "便利省时行动者",
    role: "consumer",
    color: "#78d1d8",
  },
  {
    id: "consumer-habit",
    name: "习惯锚定复购者",
    role: "consumer",
    color: "#c8a4d6",
  },
  {
    id: "consumer-outcome",
    name: "结果表现优化者",
    role: "consumer",
    color: "#f0c08d",
  },
  {
    id: "consumer-novelty",
    name: "新鲜体验探索者",
    role: "consumer",
    color: "#e8a2b2",
  },
  {
    id: "consumer-proof",
    name: "口碑比较依赖者",
    role: "consumer",
    color: "#9bbde5",
  },
  {
    id: "consumer-identity",
    name: "身份意义表达者",
    role: "consumer",
    color: "#bcb0f1",
  },
  {
    id: "consumer-occasion",
    name: "场合关系购买者",
    role: "consumer",
    color: "#e9cf7e",
  },
  {
    id: "synthesizer",
    name: "FeedbackSynthesizer",
    role: "synthesizer",
    color: "#85d8dd",
  },
  {
    id: "critic",
    name: "CriticAgent",
    role: "critic",
    color: "#ef9a78",
  },
]);

export const SAMPLE_RUN_EVENTS = Object.freeze([
  {
    id: "run-started",
    type: SANDBOX_EVENT_TYPES.RUN_STARTED,
    round: 0,
    actorId: "decision",
    headline: "示例回放启动",
    summary: "沙盘将用离线事件先演示一段营销策略搜索。",
    bubble: "先把搜索过程点亮。",
    detail: "这一版先由示例事件驱动画面，后续会把真实沙盘事件接进同一条播放链。",
  },
  {
    id: "round-1-started",
    type: SANDBOX_EVENT_TYPES.ROUND_STARTED,
    round: 1,
    actorId: "decision",
    headline: "第 1 轮开始",
    summary: "UCB 搜索先看还没有被充分探索的策略家族。",
    bubble: "先试一个降低首购阻力的方向。",
    detail: "当前演示轮次把策略家族视作搜索 arm，不把内部搜索信号写成市场预测。",
  },
  {
    id: "round-1-family",
    type: SANDBOX_EVENT_TYPES.FAMILY_SELECTED,
    round: 1,
    actorId: "decision",
    headline: "选中策略家族",
    summary: "trial_value_entry 进入 cold start。",
    bubble: "本轮探索试用门槛。",
    family: {
      id: "trial_value_entry",
      name: "试用价值入口",
      state: "cold start",
      note: "先降低第一次尝试的心理门槛，再看信任和复购是否跟得上。",
    },
    internalSearch: {
      kind: "family_selection",
      ucbScore: { value: null, display: "cold start infinity" },
      generationIntent: "cold_start",
      selectionReason: "还没完整测过，先给它一个代表性机会。",
      metricBoundary: "UCB score 是内部 family 搜索分数，不是购买率或市场预测。",
    },
  },
  {
    id: "round-1-strategy",
    type: SANDBOX_EVENT_TYPES.STRATEGY_PROPOSED,
    round: 1,
    actorId: "decision",
    headline: "DecisionAgent 出招",
    summary: "先用新手组合包和首购券把试用门槛压低。",
    bubble: "让第一次尝试更轻。",
    strategy: {
      name: "轻试用入口方案",
      familyId: "trial_value_entry",
      intent: "验证低门槛首购能否把犹豫人群推近。",
      actions: [
        { category: "Product", note: "新手组合包，突出上手简单" },
        { category: "Price", note: "首购券和明确价值解释" },
        { category: "Promotion", note: "短内容演示第一次体验" },
      ],
    },
  },
  {
    id: "round-1-value-feedback",
    type: SANDBOX_EVENT_TYPES.CONSUMER_FEEDBACK_READY,
    round: 1,
    actorId: "consumer-value",
    headline: "预算价值务实者回应",
    summary: "首购门槛变轻了，但仍会先确认是不是只靠优惠吸引。",
    bubble: "我愿意先看看，但别只会发券。",
    feedback: {
      firstImpression: "比一上来讲品牌故事更容易让我停下来看。",
      barrier: "如果优惠结束后价值理由不清楚，我不会自然回来。",
      repeat: "需要补货或使用触发，不然只像一次尝鲜。",
      competitor: "竞品给出更直接的低价时，我会重新比较。",
    },
  },
  {
    id: "round-1-trust-feedback",
    type: SANDBOX_EVENT_TYPES.CONSUMER_FEEDBACK_READY,
    round: 1,
    actorId: "consumer-trust",
    headline: "信任风险谨慎者回应",
    summary: "试用入口看懂了，但产品保障和可信证据还不够。",
    bubble: "入口轻了，信任还没站稳。",
    feedback: {
      firstImpression: "我能看懂它想让我先试一次。",
      barrier: "证据更像促销内容，不像品质保证。",
      repeat: "服务和保障清楚后才会考虑留下。",
      competitor: "熟悉品牌给出同类承诺时，我会偏向熟悉方。",
    },
  },
  {
    id: "round-1-summary",
    type: SANDBOX_EVENT_TYPES.FEEDBACK_SUMMARY_READY,
    round: 1,
    actorId: "synthesizer",
    headline: "反馈汇总完成",
    summary: "这套打法更像把首购推近，信任与复购理由还没长出来。",
    bubble: "首购更近，复购还虚。",
    synthesis: {
      moved: "预算价值务实者更愿意停下来看。",
      unmoved: "谨慎信任型人群仍在等可信证据。",
      next: "下一轮要验证风险缓释和使用后触发能不能补上。",
    },
  },
  {
    id: "round-1-critique",
    type: SANDBOX_EVENT_TYPES.CRITIQUE_READY,
    round: 1,
    actorId: "critic",
    headline: "批评者指出风险",
    summary: "当前策略容易被看成短期拉新，竞品跟价后防守薄。",
    bubble: "优惠不是护城河。",
    critique: {
      mainRisk: "过度依赖首购激励。",
      boundary: "产品真实保障没有被越界扩写，但证据仍薄。",
      next: "下一轮必须验证不加大折扣时还能靠什么留下人。",
    },
  },
  {
    id: "round-1-search-update",
    type: SANDBOX_EVENT_TYPES.SEARCH_UPDATED,
    round: 1,
    actorId: "decision",
    headline: "搜索轨迹更新",
    summary: "trial_value_entry 已探索，search memory 记录到信任和复购短板。",
    bubble: "记住这轮的短板。",
    search: {
      note: "首购推进感明显，竞品韧性证据混合。",
      families: [
        { id: "trial_value_entry", label: "已探索", tone: "promising" },
        { id: "trust_risk_reduction", label: "待验证", tone: "pending" },
        { id: "retention_habit_defense", label: "待验证", tone: "pending" },
      ],
      internalMetrics: {
        metricBoundary: "Reward、mean reward 和 UCB 相关值只解释搜索过程，不代表真实市场结果。",
        familyId: "trial_value_entry",
        reward: 0.62,
        positiveUtility: 0.78,
        riskPenalty: 0.16,
        positiveComponents: {
          trial_momentum: 0.2,
          strategy_clarity: 0.15,
          evidence_consistency: 0.05,
        },
        riskComponents: {
          brand_risk: 0.04,
          self_deception_risk: 0.08,
          execution_risk: 0.04,
        },
        appliedCaps: ["none"],
        mappingNote: "定性搜索标签经固定映射形成内部 search reward。",
        stateBefore: {
          pullCount: 0,
          rewardSum: 0,
          meanReward: 0,
          lastSelectedRound: null,
        },
        stateAfter: {
          pullCount: 1,
          rewardSum: 0.62,
          meanReward: 0.62,
          lastSelectedRound: 1,
        },
      },
    },
  },
  {
    id: "round-1-complete",
    type: SANDBOX_EVENT_TYPES.ROUND_COMPLETED,
    round: 1,
    actorId: "decision",
    headline: "第 1 轮收束",
    summary: "首购方向留下证据，也留下了下一轮要补的风险。",
    bubble: "去看信任能不能补上。",
  },
  {
    id: "round-2-started",
    type: SANDBOX_EVENT_TYPES.ROUND_STARTED,
    round: 2,
    actorId: "decision",
    headline: "第 2 轮开始",
    summary: "搜索切向另一个还未充分验证的家族。",
    bubble: "换个赢法，不只修优惠。",
  },
  {
    id: "round-2-family",
    type: SANDBOX_EVENT_TYPES.FAMILY_SELECTED,
    round: 2,
    actorId: "decision",
    headline: "新家族进入探索",
    summary: "trust_risk_reduction 被选中。",
    bubble: "这一轮先压住不信。",
    family: {
      id: "trust_risk_reduction",
      name: "信任与风险缓释",
      state: "cold start",
      note: "把品质证据、服务保障和后悔风险说清。",
    },
    internalSearch: {
      kind: "family_selection",
      ucbScore: { value: null, display: "cold start infinity" },
      generationIntent: "cold_start",
      selectionReason: "trial 已有一轮证据，信任家族还需要 cold start。",
      metricBoundary: "UCB score 是内部 family 搜索分数，不是购买率或市场预测。",
    },
  },
  {
    id: "round-2-strategy",
    type: SANDBOX_EVENT_TYPES.STRATEGY_PROPOSED,
    round: 2,
    actorId: "decision",
    headline: "DecisionAgent 换招",
    summary: "把体验证据、退换保障和使用支持摆到前面。",
    bubble: "先让承诺站稳。",
    strategy: {
      name: "信任缓释方案",
      familyId: "trust_risk_reduction",
      intent: "验证不靠更大折扣时，信任证据能否推近核心人群。",
      actions: [
        { category: "Positioning", note: "品质信任优先" },
        { category: "Product", note: "上手支持和保障承诺" },
        { category: "Channel", note: "在可信触点完成比较" },
      ],
    },
  },
  {
    id: "round-2-habit-feedback",
    type: SANDBOX_EVENT_TYPES.CONSUMER_FEEDBACK_READY,
    round: 2,
    actorId: "consumer-habit",
    headline: "习惯锚定复购者回应",
    summary: "保障更安心，但要有明确触发才会替换旧习惯。",
    bubble: "安心了，还要给我切换理由。",
    feedback: {
      firstImpression: "这轮看起来更稳，不像只在做促销。",
      barrier: "旧习惯仍方便，换掉它需要明确场景。",
      repeat: "使用支持和补货提醒会更有用。",
      competitor: "竞品如果更顺手，我仍会留下旧选择。",
    },
  },
  {
    id: "round-2-run-complete",
    type: SANDBOX_EVENT_TYPES.RUN_COMPLETED,
    round: 2,
    actorId: "synthesizer",
    headline: "示例回放完成",
    summary: "画面已经走过出招、消费者反馈、总结、批评与搜索切换。",
    bubble: "现在可以接真实沙盘流了。",
    detail: "后续真实运行会复用同一套事件播放入口。",
  },
]);
